#! /usr/bin/env bash

# cd to the directory of this script
cd "$(dirname "$0")" || exit

docker build -t qsyn-test -f docker/test.Dockerfile .

docker run --rm --security-opt seccomp=unconfined -v "$(pwd)":/app/qsyn qsyn-test "$@"
