zxRules.o: zxRules.cpp
phasegadget.o: phasegadget.cpp
pivotgadget.o: pivotgadget.cpp
simpCmd.o: simpCmd.cpp
pivot.o: pivot.cpp
simplify.o: simplify.cpp
sfusion.o: sfusion.cpp
hopf.o: hopf.cpp
id.o: id.cpp
copy.o: copy.cpp
hfusion.o: hfusion.cpp
hrule.o: hrule.cpp
bialg.o: bialg.cpp
lcomp.o: lcomp.cpp
