qsyn> ver 1
Note: verbose level is set to 1

qsyn> zxm -on
ZXMODE turn ON!

qsyn> qccread benchmark/benchmark_SABRE/large/cm82a_208.qasm

qsyn> qczxm

qsyn> zxgp
Graph 0
Inputs:        16
Outputs:       16
Vertices:      965
Edges:         1232

qsyn> zxcopy

qsyn> zxgadjoint

qsyn> zxcompose 0

qsyn> zxgprint
Graph 1
Inputs:        16
Outputs:       16
Vertices:      1898
Edges:         2448

qsyn> usage
Period time used : 0.03 seconds
Total time used  : 0.03 seconds
Total memory used: 3.727 M Bytes

qsyn> zxgs -fr
Spider Fusion Rule:           3 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   3 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   3 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           3 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           3 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Local Complementary Rule:     2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Pivot Gadget Rule:            5 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           6 iterator(s)
Pivot Rule:                   1 iterator(s)
Local Complementary Rule:     10 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           13 iterator(s)
Pivot Rule:                   2 iterator(s)
Local Complementary Rule:     2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Local Complementary Rule:     6 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Local Complementary Rule:     2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Local Complementary Rule:     2 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Local Complementary Rule:     2 iterator(s)
Phase Gadget Rule:            1 iterator(s)
Pivot Rule:                   1 iterator(s)
Local Complementary Rule:     3 iterator(s)
Pivot Rule:                   2 iterator(s)
Pivot Gadget Rule:            1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Gadget Rule:            1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Gadget Rule:            1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Pivot Gadget Rule:            1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Gadget Rule:            1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   3 iterator(s)
Identity Removal Rule:        2 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Gadget Rule:            1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   2 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)
Spider Fusion Rule:           1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        2 iterator(s)
Phase Gadget Rule:            1 iterator(s)
Pivot Rule:                   1 iterator(s)
Identity Removal Rule:        1 iterator(s)

qsyn> usage
Period time used : 1.45 seconds
Total time used  : 1.48 seconds
Total memory used: 4.383 M Bytes

qsyn> zxgp
Graph 1
Inputs:        16
Outputs:       16
Vertices:      32
Edges:         16

qsyn> zxgp -v

ID:	1	VertexType:	●	Qubit:	0	Phase:	0	#Neighbors:	1	(981, -) 
ID:	3	VertexType:	●	Qubit:	1	Phase:	0	#Neighbors:	1	(982, -) 
ID:	5	VertexType:	●	Qubit:	2	Phase:	0	#Neighbors:	1	(983, -) 
ID:	7	VertexType:	●	Qubit:	3	Phase:	0	#Neighbors:	1	(984, -) 
ID:	9	VertexType:	●	Qubit:	4	Phase:	0	#Neighbors:	1	(985, -) 
ID:	11	VertexType:	●	Qubit:	5	Phase:	0	#Neighbors:	1	(986, -) 
ID:	13	VertexType:	●	Qubit:	6	Phase:	0	#Neighbors:	1	(987, -) 
ID:	15	VertexType:	●	Qubit:	7	Phase:	0	#Neighbors:	1	(988, -) 
ID:	17	VertexType:	●	Qubit:	8	Phase:	0	#Neighbors:	1	(989, -) 
ID:	19	VertexType:	●	Qubit:	9	Phase:	0	#Neighbors:	1	(990, -) 
ID:	21	VertexType:	●	Qubit:	10	Phase:	0	#Neighbors:	1	(991, -) 
ID:	23	VertexType:	●	Qubit:	11	Phase:	0	#Neighbors:	1	(992, -) 
ID:	25	VertexType:	●	Qubit:	12	Phase:	0	#Neighbors:	1	(993, -) 
ID:	27	VertexType:	●	Qubit:	13	Phase:	0	#Neighbors:	1	(994, -) 
ID:	29	VertexType:	●	Qubit:	14	Phase:	0	#Neighbors:	1	(995, -) 
ID:	31	VertexType:	●	Qubit:	15	Phase:	0	#Neighbors:	1	(996, -) 
ID:	981	VertexType:	●	Qubit:	0	Phase:	0	#Neighbors:	1	(1, -) 
ID:	982	VertexType:	●	Qubit:	1	Phase:	0	#Neighbors:	1	(3, -) 
ID:	983	VertexType:	●	Qubit:	2	Phase:	0	#Neighbors:	1	(5, -) 
ID:	984	VertexType:	●	Qubit:	3	Phase:	0	#Neighbors:	1	(7, -) 
ID:	985	VertexType:	●	Qubit:	4	Phase:	0	#Neighbors:	1	(9, -) 
ID:	986	VertexType:	●	Qubit:	5	Phase:	0	#Neighbors:	1	(11, -) 
ID:	987	VertexType:	●	Qubit:	6	Phase:	0	#Neighbors:	1	(13, -) 
ID:	988	VertexType:	●	Qubit:	7	Phase:	0	#Neighbors:	1	(15, -) 
ID:	989	VertexType:	●	Qubit:	8	Phase:	0	#Neighbors:	1	(17, -) 
ID:	990	VertexType:	●	Qubit:	9	Phase:	0	#Neighbors:	1	(19, -) 
ID:	991	VertexType:	●	Qubit:	10	Phase:	0	#Neighbors:	1	(21, -) 
ID:	992	VertexType:	●	Qubit:	11	Phase:	0	#Neighbors:	1	(23, -) 
ID:	993	VertexType:	●	Qubit:	12	Phase:	0	#Neighbors:	1	(25, -) 
ID:	994	VertexType:	●	Qubit:	13	Phase:	0	#Neighbors:	1	(27, -) 
ID:	995	VertexType:	●	Qubit:	14	Phase:	0	#Neighbors:	1	(29, -) 
ID:	996	VertexType:	●	Qubit:	15	Phase:	0	#Neighbors:	1	(31, -) 
Total #Vertices: 32


qsyn> usage
Period time used : 0 seconds
Total time used  : 1.48 seconds
Total memory used: 4.383 M Bytes

qsyn> q -f

