#!/usr/bin/env bash
format_one() {
    clang-format -i "$1"
}
export -f format_one

lint_one() {
    clang-tidy "$1" --quiet 2>&1 | grep -v "warnings generated" | grep -v "warning generated"
}
export -f lint_one

FILES=$(find ./src -regex '.*\.[ch]pp' -type f)

# Format all files first to avoid linting errors
echo "Formatting files..."
parallel -j"$(nproc)" format_one ::: "$FILES"
echo "Linting files..."
parallel -j"$(nproc)" lint_one ::: "$FILES"
echo "Done"
