name: Makefile CI

on:
  push:
    branches: [ "main", "devt" ]
  pull_request:
    branches: [ "main", "devt" ]

jobs:
  build-and-test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: g++-10
      run: | 
          sudo apt update
          sudo apt install gcc-10 g++-10 gfortran-10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
    
    - name: configure
      run:  |
          ./configure.sh
          make linux18
      
    - name: Compile main program
      run: make -j8
      
    - name: Compile test program
      run: make test -j8
      
    - name: run tests
      run: ./RUN_ALL_TEST.sh
