name: Makefile CI

on:
  push:
    branches: [ "main", "devt" ]
  pull_request:
    branches: [ "main", "devt" ]

jobs:
  build-and-test:

    runs-on: ubuntu-22.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3
    
    - name: install openBLAS
      run: sudo apt install libopenblas-dev
      
    - name: Compile main program
      run:  |
        mkdir build && cd build
        cmake ..
        make -j16

      
    # - name: Compile test program
    #   run: make test -j8
      
    - name: run tests
      run: TERM=dumb ./RUN_ALL_TEST.sh -v
