name: llvm-clang test (Ubuntu)

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Build the test docker image
        run: docker build -t qsyn-test-clang -f docker/clang-test.Dockerfile .
      - name: Run the test docker image
        run: docker run --rm --security-opt seccomp=unconfined -v "$(pwd)":/app/qsyn qsyn-test-clang
