name: Docker test

on:
  push:
    branches: ["main", "devt"]
  pull_request:
    branches: ["main", "devt"]

jobs:
  docker-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Run tests in Docker
        run: ./RUN_TESTS_DOCKER -dv
