name: Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-22.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Check source formatting
        run: make format-check
